services:
  backend:
    build: ./backend
    container_name: alpha_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://amulya_saas_db_user:9BQdfyTzjcc7NfjiBgB7oDEYguHB3bc0@dpg-d57824je5dus73d6gua0-a.singapore-postgres.render.com/amulya_saas_db?ssl=true
      - JWT_SECRET=any_random_string_here
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: alpha_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend